[package]
name = "gitsplode"
version = "0.1.0"
authors = ["chip <chip@chip.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
git = { path = "../git" }
